name: Elite Equine - High Performance Nutrition
favicon: null
layout_spectrum: 0.7459871175233275
typography_spectrum: 0.2705273211468011
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7362146542873234
  lightness: 0.869587262859568
  saturation: 0.7863723081536591
  rhythmicContrast: 0.3405809698160738
purpose: []
